### PR TITLE
[CXKAN-999] add `partition_key` to `post` and `post_gzipped`

### PR DESCRIPTION
**Pull request by Crunch09**
To enable customisation of the `partition_key` for every record.

### CODE REVIEW

**Comment by pedrocunha** [comment]
Hi @Crunch09 what's the reason for this change? Are you going to be reading directly the kinesis stream?

**Comment by Crunch09** [comment]
Hey @pedrocunha ,
the reason for this change is that @mudim wants us to use the `id` as a `partition_key` so that he can group the records by `id` instead of the current `seconds since epoch`.

**Review by me — APPROVED** [review]
Looks good. Of course we will want to deploy https://github.com/deliveroo/data-sink/pull/45 before this!

**Comment by pedrocunha** [comment]
if you partition by id does it means records are stored in s3 using ids as the folders? Sorry I am still not following this change unless @mudim is going to connect directly to the kinesis stream?

**Pull request merged**
